### ISSUE TITLE
 Sample click_game_object. Registers clicks outside of sprite.

### ISSUE THREAD

**Issue by BreadSniper** [britzl/publicexamples#10]
Steps:
1. Set letterbox projection in `init` method.
2. Use goput script to handle clicks on sprite.
3. Launch game.
4. Stretch game in horizontal direction. (notice: black lines appear from left and right side)
5. Click slightly outside from the left or from the right of the sprite.

Actual result: click registers. The script doesn't take into consideration the black lines width created by letterbox projection. Action.x is zero at the start of black line, and not my background.
Expected result: click registers only when the sprite is clicked.

```lua
if action.x >= pos.x - scaled_size.x / 2 and action.x <= pos.x + scaled_size.x / 2 and action.y >= pos.y - scaled_size.y / 2 and action.y <= pos.y + scaled_size.y / 2 then
	return sprite_data.callback(sprite_data.go_url, action_id, action)
end
```

From code above:
Button offset is `pos.x - scaled_size.x / 2`.
And mouse offset is `action.x`.

<img width="556" alt="Screen Shot 2019-04-14 at 1 48 10 PM" src="https://user-images.githubusercontent.com/23015779/56091915-c3e67100-5ebd-11e9-9e6a-0942a13af9b4.png">

**Comment by britzl** [comment]
Added a disclaimer to the example. The example is created for the default stretch projection. You should use an alternative solution such as [defold-input](https://github.com/britzl/defold-input) and the cursor module to solve the problem easily.

**Comment by BreadSniper** [comment]
Hmm... I just tried the cursor module, but it doesn't solve the issue. The behavior is basically the same with this module. The clicks are registered outside the button. @britzl

**Comment by BreadSniper** [comment]
@britzl Should I open this issue in `cursor` module?

**Comment by britzl** [comment]
The cursor module works using collision objects and it should work as long as you translate screen to world coordinates properly. I guess the best solution for you to get proper screen to world translation is to use either RenderCam or Defold-Orthographic (two camera solutions in the Asset Portal). Both provide functions to convert screen to world coordinates that take into account the view projection.

**Comment by BreadSniper** [comment]
Thanks! Will try that.
