### ISSUE TITLE
[Question] Why is click and drag example removed?

### ISSUE THREAD

**Issue by gmertk** [britzl/publicexamples#5]
Hey @britzl, 
I'm looking for a way to detect clicks on moving game objects.

I've found out these two examples: click_game_object and click_and_drag. 
Looking at the git history; click_and_drag seems to create a collision object and detect collisions with other objects. 
However, you removed this example. Is it because click_game_object's approach is the preferred way of doing this?

**Comment by britzl** [comment]
Hi! I've created [a separate Defold library project called defold-input](https://github.com/britzl/defold-input) to simplify a lot of day-to-day input handling in Defold games. The library project can do cursor handling with picking and dragging of game objects, input state mapping, gesture detection and so on. Each feature is in a separate script and module and should be really easy to use. Let me know if you need any help with this!
