### ISSUE TITLE
simple_ai, slerp and weird rotations

### ISSUE THREAD

**Issue by tferreira** [britzl/publicexamples#6]
Hello!

I started a RPG game project using your simple AI algorithm, and I have some weird issues when the zombies are close to their target, they start spinning. I can't find a nice way to prevent them from rotating at all.

It is also slightly noticeable in your demo. Is this caused by the slerp rotation ?

Thank you.

**Comment by britzl** [comment]
The code for doing the rotation is very basic. It will always interpolate between current and target angle with the same `t` value regardless if the needed rotation is large or small. This results in a faster initial rotation when the rotation is large. You could perhaps fiddle with the `t` value and adjust it based on amount of rotation needed or you could always rotate a fixed amount in the shortest direction.

**Comment by tferreira** [comment]
Thank you for your answer, I'll try to make that `t` value dynamic depending on the size of the rotation. But indeed that's a bit complex for a simple rotation.
